name: PvPTitles
main: com.gmail.mikeundead.PvPTitles
version: 1.2.9
commands:
   rank:
      description: Shows your current stats
      usage: /rank
   ladder:
      description: Shows the top 5 players
      usage: /ladder